### PR TITLE
Gem replacement vulnerability and mitigation

### PR DESCRIPTION
**Pull request by johnsyweb**
# Context

RubyGems.org gem replacement vulnerability: http://blog.rubygems.org/2016/04/06/gem-replacement-vulnerability-and-mitigation.html

# Change

- Add a note about this vulnerability (unaffected)

### CODE REVIEW

**Comment by createdbypete** [comment]
:+1:

**Comment by jacobbednarz** [comment]
Probably worth starting to sign commits/tags now :stuck_out_tongue: ?

**Comment by johnsyweb** [comment]
@jacobbednarz Worth considering for sure. Unsure how it would have helped with this issue though.

**Comment by jacobbednarz** [comment]
It will allow you to quickly verify the commits since the vulnerability was discovered and ensure when you re-push, they are all legit. Avoiding some manual steps.

**Comment by stevehodgkiss** [comment]
👍

**Pull request merged**
