### PR TITLE
Add note on storing the results of `#test`

### PR DESCRIPTION
**Pull request by johnsyweb**
Context
-------

I read [A Tale of Security Gone Wrong](http://gavinmiller.io/2016/a-tale-of-security-gone-wrong/).

Change
------

Add note on storing the results of `#test`

### CODE REVIEW

**Comment by salamagd** [comment]
:+1: I think it's fair enough that, when there's a potential for a glaring security issue that is non-obvious and easily avoided, the maintainers of a gem that's popular/widely adopted within the Ruby community should provide guidance around it. I don't expect that everyone using the gem would have a deep understanding of the underlying crypto concepts, nor should they be expected to.

**Comment by jimmyjazz** [comment]
@johnsyweb I'm +1 on not storing the entropy value alongside the user data for the reasons described in the article, but I think you might want to inline the pertinent advice rather than make everyone read the article. e.g. "storing the entropy of an encrypted or hashed value provides information that can make breaking the encryption/hashing orders of magnitude easier for an attacker. Don't give them the leg up."

**Comment by johnsyweb** [comment]
Great feedback, thanks @salamagd & @jimmyjazz

**Comment by twe4ked** [comment]
:+1:

**Pull request merged**
